#ifndef FINANCETRACKER_PRIVATE_H_INCLUDED
#define FINANCETRACKER_PRIVATE_H_INCLUDED

#define NEW_TRANSACTION   1
#define VIEW_TRANSACTION  2
#define VIEW_SUMMARY      3
#define GET_INSIGHTS      4
#define EXIT_SYSTEM       5

#define BEEP   Beep(1000, 1000)
#define BEEP_DONE  Beep(1000, 500)

#endif // FINANCETRACKER_PRIVATE_H_INCLUDED
